### ISSUE TITLE
Dynamic DataTables - Not working

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-dynamic-services#1]
The [dynamic dataTables](https://github.com/app-generator/django-dynamic-datatb) library needs to updated in order to work on this project.

How to test it:

- start the app (manual set up or Docker)
  - ` $ docker-compose up --build`
- Navigate to http://localhost:5085/datatb/product2/
  - The dynamic view is created with JS errors: `TypeError: dataTable.columns is not a function`
- Navigate to http://localhost:5085/datatb/product/ (another model)
  - This view is broken (backend error): `Related Field got invalid lookup: icontains` 

Both models are defined in `home/models` and the difference between them is the fact that `Product2` is isolated and dynamic view works. 

The broken view that tries to render data for `Product` uses a model referenced by `Sales`.  

Both issues need a fix. 
We will see right after for other Issues.

Ty!

**Comment by Mortrest** [comment]
Hello
JS bug was because of breaking changes of simple-datatable libarary. I fix the version number to avoid this problem again.
Backend error fixed by filtering non-RelatiedField fields (1-1, 1-M, M-1 or M-M).
Please review and test [pull request](https://github.com/app-generator/django-dynamic-datatb/pull/2) and merge it.

**Comment by app-generator** [comment]
wow ...

**Comment by app-generator** [comment]
validated. ty guys.

**Comment by app-generator** [comment]
Hello @Mortrest, here is the next thing: 
https://github.com/app-generator/django-dynamic-datatb/issues/3
